//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public invoice()
        {
            this.invoice_detail = new HashSet<invoice_detail>();
        }
    
        public int invoiceNumber { get; set; }
        public string invoiceDate { get; set; }
        public string customerName { get; set; }
        public Nullable<int> invoiceTotalValue { get; set; }

        public virtual ICollection<invoice_detail> invoice_detail { get; set; }
    }
}
