//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_detail
    {
        public int articleId { get; set; }
        public string articleName { get; set; }
        public Nullable<double> articlePrice { get; set; }
        public Nullable<int> invoiceNumber { get; set; }
    
        public virtual invoice invoice { get; set; }
    }
}
